### ISSUE TITLE
Can't compile on debian

### ISSUE THREAD

**Issue by bodji** [jmeichle/pidgin-embeddedvideo-imageview#3]
Two errors : 
Makefile.am: required file `./README' not found

After creating dummy README file : 
mv -f .deps/libwebsites_la-collegehumor.Tpo .deps/libwebsites_la-collegehumor.Plo
mv: cannot stat `.deps/libwebsites_la-collegehumor.Tpo': No such file or directory

**Comment by jmeichle** [comment]
Unfortunately this is not my code, or rather I am not an author in here, so I have no plans on maintaining this. I put this repo up just as a place to host it since it is a hard to find/modified copy of pidgin-imageview.
